'use client';
import {useSearchParams} from 'next/navigation';
import {useRouter} from './navigation';
import Link from './navigation';
import {Check,ArrowRight,Layers3} from 'lucide-react';
import {toast} from 'sonner';
import {useSolace} from '@/lib/solace/store';
import {templates} from '@/lib/solace/data';
import {Heading,Pick,Badge,Action} from './ui';
import {ProgramTabs} from './program-content';
import {activationIssues} from './engagements';
export function Programs(){const {data,setData,clientId}=useSolace();const params=useSearchParams();const router=useRouter();const ens=data.engagements.filter(e=>clientId==='all'||e.clientId===clientId);const en=ens.find(e=>e.id===params.get('id'))||ens[0];const issues=en?activationIssues(data,en.id):[];return <><Heading eyebrow="THOUGHTFULLY PLANNED. PERSONALLY DELIVERED." title="Configure program" description="Build a wellbeing experience around the people who matter." action={en?<Link className="button secondary" href={'/engagements?id='+en.id}>Open lifecycle <ArrowRight size={16}/></Link>:undefined}/><div className="template-grid">{templates.map((t,i)=><div className="template-card" key={t.name}><span className={'template-icon tone-'+i}><Layers3 size={22}/></span><div><small>PROGRAM TEMPLATE · {t.duration.toUpperCase()}</small><h3>{t.name}</h3><p>{t.description}</p><div className="tags">{t.tags.map(tag=><span key={tag}>{tag}</span>)}</div></div></div>)}</div><div className="configuration-bar"><div><span className="eyebrow">CONFIGURING ENGAGEMENT</span><Pick label="Select engagement to configure" value={en?.id||''} onChange={id=>router.push('/programs?id='+id)} options={ens.map(e=>({value:e.id,label:e.name}))}/></div>{en&&<><Badge>{en.status}</Badge><div className="config-summary">{4-issues.length} / 4 essentials ready</div><Action secondary onClick={()=>toast.success('All program changes are saved automatically in this browser.')}>Save draft</Action><Action disabled={en.status!=='Draft'} onClick={()=>{if(issues.length)return toast.error(issues.join('. '));setData(d=>({...d,engagements:d.engagements.map(e=>e.id===en.id?{...e,status:'Active'}:e)}));toast.success('Engagement activated')}}>{en.status==='Draft'?'Activate engagement':en.status+' engagement'}</Action></>}</div>{en?<><div className="setup-checklist">{['Employees enrolled','Pre-assessment','Post-assessment','Activities scheduled'].map((label,i)=>{const ok=[data.employees.some(e=>e.engagementId===en.id&&e.status==='Active'),data.assessments.some(a=>a.engagementId===en.id&&a.phase==='Pre-assessment'),data.assessments.some(a=>a.engagementId===en.id&&a.phase==='Post-assessment'),data.events.some(v=>v.engagementId===en.id)][i];return <span className={ok?'done':''} key={label}><span>{ok?<Check size={12}/>:i+1}</span>{label}</span>})}<Link href={'/employees?client='+en.clientId}>Manage enrollment <ArrowRight size={14}/></Link></div><ProgramTabs engagementId={en.id}/></>:<div className="empty"><h3>Create an engagement first</h3><Link className="button" href="/engagements?new=1">Create engagement</Link></div>}</>}
